# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170603_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortmeurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortmeurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
